package:
  name: diting
  version: "0.5"

source:
  git_url: https://github.com/xuechunxu/DiTing.git

build:

requirements:
  run:
    - bbmap 38.79
    - bwa 0.7.17
    - hmmer 3.3
    - matplotlib 3.2.1
    - megahit 1.1.3
    - opencv 4.2.0
    - pandas 1.0.3
    - pillow 7.0.0
    - prodigal 2.6.3
    - python 3.7.6
    - seaborn 0.10.0


about:
  home: https://github.com/xuechunxu/DiTing
  summary: A pipeline to infer and compare biogeochemical pathways in metagenomic data
  license: GPL-3.0