{% set version = "0.6" %}

package:
  name: diting
  version: {{ version }}

source:
  git_url: https://github.com/xuechunxu/DiTing.git

build:
  number: 0

requirements:
  host:
    - python >=3.6
  run:
    - bbmap >=38.0
    - bwa >=0.7
    - hmmer 3.*
    - matplotlib >=3.1
    - megahit >=1.1.2
    - numpy >=1.18
    - opencv >=4.1
    - pandas >=0.25
    - pillow >=7.0
    - prodigal 2.6.*
    - python >=3.6
    - seaborn >=0.9


about:
  home: https://github.com/xuechunxu/DiTing
  summary: A pipeline to infer and compare biogeochemical pathways in metagenomic data
  license: GPL-3.0